feat(validation): add unit test for max value validator
globalbrain/sefirot pull request #36
Opened 2021-02-02 09:23 UTC by ryo-gk

close #35 .
Add `maxValue` validation.

2021-02-02 09:32 UTC, kiaking commented on lib/validation/validators/maxValue.ts
> +export default function maxValue(value: any, max: number): boolean {
`value`は`value: number`でもいいかも。数値以外入ってきてもできることないと思うので 😳

2021-02-02 09:36 UTC, kiaking commented on test/validation/validators/maxValue.spec.ts
> +      expect(maxValue(check[0], check[1])).toBe(check[2])
引数に渡す`check[0]`と`check[1]`が逆かも？ `check[0]`が`value`で、`check[1]`が`max`、だと思うので。

2021-02-02 09:37 UTC, kiaking commented on test/validation/validators/maxValue.spec.ts
> +      [256, 257, false],
これは`[257, 256, false]`が正解？（配列インデックスの0と1が逆？）

2021-02-02 09:46 UTC, ryo-gk commented on lib/validation/validators/maxValue.ts
> +export default function maxValue(value: any, max: number): boolean {
たしかにそうですね。number に変えます😂

2021-02-02 09:48 UTC, kiaking commented on test/validation/validators/maxValue.spec.ts
> +      expect(maxValue(check[0], check[1])).toBe(check[2])
あ、`cheks`の定義でミスがあって、こっちは正しいのか・・・！

2021-02-02 09:58 UTC, ryo-gk commented on test/validation/validators/maxValue.spec.ts
> +      [256, 257, false],
ミスです。
`[256, 255, false]` と書くつもりでした。

2021-02-02 09:59 UTC, ryo-gk commented on test/validation/validators/maxValue.spec.ts
> +      expect(maxValue(check[0], check[1])).toBe(check[2])
そうでした 🙇

2021-02-02 10:12 UTC, kiaking commented on test/validation/validators/maxValue.spec.ts
> +      [256, 257, false],
👍

2021-02-02 10:12 UTC, kiaking commented on test/validation/validators/maxValue.spec.ts
> +      expect(maxValue(check[0], check[1])).toBe(check[2])
👍

2021-02-02 23:24 UTC, kiaking requested changes
いいね！ 2つコメントしました。確認お願いしまーす！ 🤝

2021-02-02 23:24 UTC, kiaking commented on lib/validation/rules/maxValue.ts
> +export default function maxValue(max: string, message?: string): Rule {
`max`は`number`ですな！

2021-02-02 23:24 UTC, kiaking commented on lib/validation/rules/maxValue.ts
> +    validate: (value, data) => baseMaxValue(value, data[max])
ここは

```ts
validate: value => baseMaxValue(value, max)
```

ですね！ `validate`メソッドは、第一引数に入力値、第二引数にデータオブジェクト全体を受け取ります。例えば、以下のようなフォームがあった場合

```ts
const { data } = useData({
  name: '',
  email: ''
})

const validation = useValidation(data, {
  name: [required()],
  email: [required(), email()]
})
```

この時、`name`の`rule.validate`メソッドは、第一引数に`data.name`の値を、第二引数に`data`を受け取る感じです。

基本、第二引数はその項目以外の入力を参照する必要がある場合に使います。例えば`sameAs`（他の項目と内容が同じことを確認する）バリデーションとか。今回の`maxValue`では他の項目を参照する必要がないので、上述のように

```ts
validate: value => baseMaxValue(value, max)
```

で十分、というわけですな。

2021-02-03 02:52 UTC, kiaking approved these changes
Niiiiice!

2021-02-03 02:52 UTC, merged